#!/bin/sh
set -e

. /usr/share/debconf/confmodule

file="$1"

host="ppa.launchpad.net"
codename="artful"
dists="main"

# Don't test mirror if no network selected in netcfg
echo "deb [trusted=yes] http://$host/tobetter/ppa/ubuntu $codename $dists" >> $file
if db_get netcfg/dhcp_options && \
   [ "$RET" = "Do not configure the network at this time" ]; then
	CODE=9
else
	CODE=0
	export ASV_TIMEOUT="-o Acquire::http::Timeout=30"
	if ! apt-setup-verify --from $PROGRESS_FROM --to $PROGRESS_TO $file; then
		db_subst apt-setup/service-failed HOST "$host"
		db_input critical apt-setup/service-failed || true
		if ! db_go; then
			exit 10 # back up
		fi
		CODE=9
	fi
fi

deb_src="deb-src"
db_get apt-setup/enable-source-repositories
if [ "$RET" = false ]; then
	deb_src="# deb-src"
fi

echo "$deb_src [trusted=yes] http://$host/tobetter/ppa/ubuntu $codename $dists" >> $file

exit $CODE
